import Providers from "@/components/Providers";
import "./globals.css";
import { ubuntu } from "./fonts";
import Navbar from "@/components/Navbar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" className="">
      <Providers>
        <body className={`${ubuntu.className} bg-[#0A092D] text-white`}>
          <div className="bg-[#0A092D] min-h-screen">
            <Navbar />
            {children}
          </div>
        </body>
      </Providers>
    </html>
  );
}
